apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgresql
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: todo-postgresql-hl
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgresql
  template:
    metadata:
      labels:
        app: todo-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgresql
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    app: todo-postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgresql-hl
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: todo-postgresql
  ports:
    - port: 5432
      targetPort: 5432