FROM nginx:1.27-alpine

# Удаляем дефолтный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш конфиг
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем статику
COPY web/index.html /usr/share/nginx/html/
COPY web/docs.html /usr/share/nginx/html/
COPY web/assets/ /usr/share/nginx/html/assets/

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s \
    CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
