apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/Subcore/todo-app-v2.git
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: todo-postgresql
  namespace: todo-app
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "18.5.11"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: postgres
      password: "REDACTED_PASSWORD"
      postgresPassword: "REDACTED_PASSWORD"
      database: todo_db
    primary:
      persistence:
        enabled: true
        size: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: todo-app
  namespace: todo-app
spec:
  interval: 5m
  dependsOn:
    - name: todo-postgresql
  chart:
    spec:
      chart: deploy/helm/todo-app
      sourceRef:
        kind: GitRepository
        name: todo-app
        namespace: flux-system
  values:
    image:
      tag: "main-20260416T100647-63e16bf" # {"$imagepolicy": "flux-system:todo-api:tag"}
    web:
      image:
        tag: "main-20260416T100647-63e16bf" # {"$imagepolicy": "flux-system:todo-web:tag"}
  valuesFrom:
    - kind: ConfigMap
      name: todo-app-values
      optional: false
