apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-values
  namespace: todo-app
data:
  values.yaml: |
    image:
      repository: ghcr.io/subcore/todo-api
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: ghcr-secret

    web:
      image:
        repository: ghcr.io/subcore/todo-web
        pullPolicy: IfNotPresent
      nodeSelector:
        workload: web
      tolerations:
        - key: workload
          operator: Equal
          value: web
          effect: NoSchedule

    postgresql:
      enabled: false

    db:
      host: todo-postgresql
      port: "5432"
      name: todo_db
      user: postgres
      sslmode: disable

    api:
      nodeSelector:
        workload: api
      tolerations:
        - key: workload
          operator: Equal
          value: api
          effect: NoSchedule
