apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-values
  namespace: todo-app
data:
  values.yaml: |
    image:
      repository: ghcr.io/subcore/todo-api
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: ghcr-secret

    web:
      image:
        repository: ghcr.io/subcore/todo-web
        pullPolicy: IfNotPresent

    ingress:
      enabled: true
      className: nginx
      host: 34.87.115.233.nip.io

    postgresql:
      enabled: false

    existingSecret: todo-db-credentials

    db:
      host: todo-postgresql
      port: "5432"
      name: todo_db
      user: postgres
      sslmode: disable
