image:
  repository: localhost:5000/todo-api
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

web:
  baseHref: "/web/"
  image:
    repository: localhost:5000/todo-web
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

enableSwagger: true

ingress:
  enabled: true
  className: nginx
  host: todo.local

db:
  host: todo-postgresql
  port: "5432"
  name: todo_db
  user: postgres
  password: postgres
  sslmode: disable

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

postgresql:
  auth:
    username: "postgres"
    password: postgres
    postgresPassword: postgres
    database: todo_db
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
