image:
  repository: ghcr.io/subcore/todo-api
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

web:
  image:
    repository: ghcr.io/subcore/todo-web
    tag: "latest"
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: 34.87.120.234.nip.io

db:
  host: todo-postgresql
  port: "5432"
  name: todo_db
  user: postgres
  password: "TodoGCP2026!"
  sslmode: disable
