apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
data:
  DB_HOST: {{ include "todo-app.dbHost" . | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_SSLMODE: {{ .Values.db.sslmode | quote }}
  PORT: "8080"
  GIN_MODE: "release"
  ENABLE_SWAGGER: {{ .Values.enableSwagger | default "false" | quote }}
