replicaCount: 2

image:
  repository: todo-api
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

database:
  host: todo-db-postgresql
  port: 5432
  user: postgres
  password: postgres
  name: todo_db
  sslmode: disable

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
