apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ingress-nginx/helmrelease.yaml
  - todo-app/namespace.yaml
  - todo-app/values.yaml
  - todo-app/helmrelease.yaml
  - todo-app/image-automation.yaml
